### ISSUE TITLE
FIM阶段处理流程

### ISSUE THREAD

**Issue by Zongjy** [yiyepiaoling0715/codellm-data-preprocess-pipeline#1]
请问流程图中FIM阶段：
1. **AR文件**模块是什么意思？
2. 对单行代码块的**topN长度策略**是指什么？

**Comment by yiyepiaoling0715** [comment]
> 请问流程图中FIM阶段：
> 
> 1. **AR文件**模块是什么意思？
> 2. 对单行代码块的**topN长度策略**是指什么？

1.ar指不做fim处理的 文件， ar一般指 autogressive自回归，从前到后，所以此处用这个名字
2. 单行代码块 我们的策略是 长度优先，越长的学习难度越高，这是 理想中的middle，但是 因为 实际最长的不一定合适，比如 string='', print(xxx), 这种，所以会通过 长度处于top1/3的范围内做过滤，然后随机选
